#!/usr/bin/python
import sys
import os
import pickle
import time
HOME="/home/paul";
class FromTo:
	def __init__(self,frm,to,day):
		self.frm=frm;
		self.to=to;
		self.refresh_day=day;
def Reset():
	confirm=raw_input("Are you sure you want to reset (y for yes):");
	if(confirm=="y"):
		fp=open(HOME+"/.usage/Current","w");
		fp.write("0");
		fp.close();
		fp=open(HOME+"/.usage/Total","w");
		fp.write("0");
		fp.close();
def Settime():
	from_time=int(raw_input("Enter the starting hour of free usage(eg :130 for 1:30 am) : \n"))
	to_time=int(raw_input("Enter the ending hour of free usage(eg :130 for 1:30 am) : \n"))
	day=int(raw_input("Enter the day of month in which the values has to be refreshed : \n"))
	fp=open(HOME+"/.usage/Freetime","w");
	freetime=FromTo(from_time,to_time,day)
	os.system("bash Resetcron "+str(day));	
	pickle.dump(freetime,fp)
	fp.close()
def Usage():
	fp=open(HOME+"/.usage/Current","r");
	usage=int(fp.read());
	fp.close();
	fp=open(HOME+"/.usage/Total","r");
	usage=usage+int(fp.read());
	fp.close();
	s=1000000000;
	while(s>1):
		if((usage/s)>1):
			if(s==1000000000):
				print str((float)(usage)/s)+" GB";
				break;
			elif(s==1000000):
				print str((float)(usage)/s)+" MB";
				break;
			elif(s==1000):
				print str((float)(usage)/s)+" KB";
				break;
			else :
				print str((float)(usage)/s)+" B";
				break;
		s=s/1000;
def Help():
	print "-c for changing the settings\
	       -h for help\
	       -u for usage info\
	       -r for reset"
try:
	sys.argv[1]
except IndexError :
	Help()
	sys.exit()
if(sys.argv[1]=="-r"):
	Reset();
elif(sys.argv[1]=="-u"):
	Usage();
elif(sys.argv[1]=="-c"):
	Settime();
elif(sys.argv[1]=="-h"):
	print Help()
else:
	Help()
